//Productos
let productosEnStock = [
    {id: 1, nombre: "Naruto #1", tipo: "manga", anime: "Naruto", img: '/img/narutovol1.jpg', precio: 575},
    {id: 2, nombre: "Naruto #2", tipo: "manga", anime: "Naruto", img: '/img/naruto-vol-2.jpg', precio: 575},
    {id: 3, nombre: "Naruto #3", tipo: "manga", anime: "Naruto", img: '/img/narutovol3.jpg', precio: 575},
    {id: 4, nombre: "Naruto #4", tipo: "manga", anime: "Naruto", img: '/img/narutovol4.jpg', precio: 575},
    {id: 5, nombre: "Naruto #5", tipo: "manga", anime: "Naruto", img: '/img/narutovol5.png', precio: 575},
    {id: 6, nombre: "Naruto #6", tipo: "manga", anime: "Naruto", img: '/img/narutovol6.jpg', precio: 575},
    {id: 7, nombre: "Naruto #7", tipo: "manga", anime: "Naruto", img: '/img/narutovol7.jpg', precio: 575},
    {id: 8, nombre: "Naruto #8", tipo: "manga", anime: "Naruto", img: '/img/narutovol8.jpg', precio: 575},
    {id: 9, nombre: "Demon Slayer #1", tipo: "manga", anime: "Demon Slayer", img: '/img/demon1.jpg', precio: 495},
    {id: 10, nombre: "Demon Slayer #2", tipo: "manga", anime: "Demon Slayer", img: '/img/demon2.jpg', precio: 495},
    {id: 11, nombre: "Demon Slayer #3", tipo: "manga", anime: "Demon Slayer", img: '/img/demon3.jpg', precio: 495},
    {id: 12, nombre: "Demon Slayer #4", tipo: "manga", anime: "Demon Slayer", img: '/img/demon4.jpg', precio: 495},
    {id: 13, nombre: "Demon Slayer #5", tipo: "manga", anime: "Demon Slayer", img: '/img/demon5.jpg', precio: 495},
    {id: 14, nombre: "Demon Slayer #6", tipo: "manga", anime: "Demon Slayer", img: '/img/demon6.jpg', precio: 495},
    {id: 15, nombre: "Demon Slayer #7", tipo: "manga", anime: "Demon Slayer", img: '/img/demon7.jpg', precio: 495},
    {id: 16, nombre: "Demon Slayer #8", tipo: "manga", anime: "Demon Slayer", img: '/img/demon8.jpg', precio: 495},
    {id: 17, nombre: "Seven Deadly Sins #1", tipo: "manga", anime: "Seven Deadly Sins", img: '/img/nanatsu1.jpg', precio: 550},
    {id: 18, nombre: "Seven Deadly Sins #2", tipo: "manga", anime: "Seven Deadly Sins", img: '/img/nanatsu2.jpg', precio: 550},
    {id: 19, nombre: "Seven Deadly Sins #3", tipo: "manga", anime: "Seven Deadly Sins", img: '/img/nanatsu3.jpg', precio: 550},
    {id: 20, nombre: "Seven Deadly Sins #4", tipo: "manga", anime: "Seven Deadly Sins", img: '/img/nanatsu4.jpg', precio: 550},
    {id: 21, nombre: "Seven Deadly Sins #5", tipo: "manga", anime: "Seven Deadly Sins", img: '/img/nanatsu5.jpg', precio: 550},
    {id: 22, nombre: "Seven Deadly Sins #6", tipo: "manga", anime: "Seven Deadly Sins", img: '/img/nanatsu6.jpg', precio: 550},
    {id: 23, nombre: "Seven Deadly Sins #7", tipo: "manga", anime: "Seven Deadly Sins", img: '/img/nanatsu7.jpg', precio: 550},
    {id: 24, nombre: "Seven Deadly Sins #8", tipo: "manga", anime: "Seven Deadly Sins", img: '/img/nanatsu8.jpg', precio: 550},
    {id: 25, nombre: "Attack on Titan #1", tipo: "manga", anime: "Attack on Titan", img: '/img/snk1.jpg', precio: 600},
    {id: 26, nombre: "Attack on Titan #2", tipo: "manga", anime: "Attack on Titan", img: '/img/snk2.jpg', precio: 600},
    {id: 27, nombre: "Attack on Titan #3", tipo: "manga", anime: "Attack on Titan", img: '/img/snk3.jpg', precio: 600},
    {id: 28, nombre: "Attack on Titan #4", tipo: "manga", anime: "Attack on Titan", img: '/img/snk4.jpg', precio: 600},
    {id: 29, nombre: "Attack on Titan #5", tipo: "manga", anime: "Attack on Titan", img: '/img/snk5.jpg', precio: 600},
    {id: 30, nombre: "Attack on Titan #6", tipo: "manga", anime: "Attack on Titan", img: '/img/snk6.jpg', precio: 600},
    {id: 31, nombre: "Attack on Titan #7", tipo: "manga", anime: "Attack on Titan", img: '/img/snk7.jpg', precio: 600},
    {id: 32, nombre: "Attack on Titan #8", tipo: "manga", anime: "Attack on Titan", img: '/img/snk8.jpg', precio: 600},
]